### PR TITLE
Main

### PR DESCRIPTION
**Pull request by ErlendT**
Added possibility of using secure connectivity settings in databricks

### CODE REVIEW

**Comment by hknutsen** [comment]
Is the idea to take control of resources using Terraform, instead of letting Azure do everything automatically? 🤔

**Comment by hknutsen** [comment]
Is it possible to hardcode the `custom_parameters` block? Then create individual variables for each argument inside it? Might simplify usage of this module.

**Comment by ErlendT** [comment]
> Is the idea to take control of resources using Terraform, instead of letting Azure do everything automatically? 🤔

No just setting to set the necessary settings to run without [public ip](https://learn.microsoft.com/en-us/azure/databricks/security/network/secure-cluster-connectivity) on clusters etc. I share your confusion as the custom parameters block should probably be split into different variables on the provider. But i guess it just follows the same pattern as the rest [api](https://learn.microsoft.com/en-us/rest/api/databricks/workspaces/create-or-update?tabs=HTTP#workspacecustomparameters)

> Is it possible to hardcode the `custom_parameters` block? Then create individual variables for each argument inside it? Might simplify usage of this module.

Probably, will check and implement.

**Comment by ErlendT** [comment]
Changes are applied in #35

**Pull request closed without merging**
