### PR TITLE
refactor: update variable descriptions

### PR DESCRIPTION
**Pull request by hknutsen**
Reorder and group similar variables, and update descriptions to clarify their use.

Also updated vNet and subnet variables to refer to correct identifiers (name vs ID), as described in [this comment](https://github.com/equinor/terraform-azurerm-databricks/pull/35#pullrequestreview-2082089394).

### CODE REVIEW

**Comment by hknutsen** [comment]
@equinor/terraform-baseline Tried my best to update variables according to our best practices. Any comments?

**Comment by hknutsen** [comment]
@ErlendT tried my best to update variables according to our best practices. Any comments?

**Comment by hknutsen** [comment]
I still think this is a relevant update, so repoening.

**Comment by hknutsen** [comment]
@ErlendT Any comments here?

**Review by ErlendT — APPROVED** [review]

**Pull request merged**
